STD_ERR: 0.001
VMC_NCONFIG: 100000
MOLECULES: ['P', 'S', 'Cl', 'Ar', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr']
METHODS: ['HF']
BASES: ['def2-QZVP']
JASTROWS: ['8_8_44']
